# Notes_application

problems:

Если запускать python3 manage.py test запускаются тесты
